Update kubernetes configurations

diff --git a/src/scripts/pgsql b/src/scripts/pgsql
--- a/src/scripts/pgsql
+++ b/src/scripts/pgsql
@@ -12,6 +12,11 @@ if [[ ! $(pg_isready) ]]; then
     exit 1
 fi
 
+if [[ $( psql -tAc "SELECT 1 FROM pg_database WHERE datname='DB_NAME'" ) = '1' ]]
+    echo "Connection to server failed" 1>&2
+    exit 1
+fi
+
 #
 # Initiate database
 #
